pipeline {
  agent any
  environment {
        VIRTUAL_ENV = "${env.WORKSPACE}/venv"
    }
  stages {
    stage('build') {
      steps {     
bat '''
set PATH=${VIRTUAL_ENV}/bin:${PATH}
pip install -r requirements.txt
'''
      }
    }
    stage('test') {
      steps {
bat '''
set PATH=${VIRTUAL_ENV}/bin:${PATH}
python engine_test.py
'''
      }
      post {
        always {
          junit '**/test-reports/*.xml'
        }
      }
    }
  }
}
